on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  ANGULAR_IMAGE_NAME: social-login-app-client
  ANGULAR_CONTAINER_NAME: social-login-app-client
  ANGULAR_DEPLOYMENT_NAME: social-login-app-client
  SPRING_BOOT_IMAGE_NAME: social-login-app-server
  SPRING_BOOT_CONTAINER_NAME: social-login-app-server
  SPRING_BOOT_DEPLOYMENT_NAME: social-login-app-server
jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    # OS specific syntax should be used to access the environment variables. Specify the shell as bash to use same syntax across multiple OSes
    #- name: Specify the shell as bash
    #  run: chsh -s /bin/bash

    - name: Checkout main
      uses: actions/checkout@main

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Provide permission to run mvnw
      run: chmod +x ./spring-boot-oauth2-social-login/mvnw

    - name: Build and push Angular Image
      id: angular_docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./angular-11-social-login
        file: ./angular-11-social-login/Dockerfile
        push: true
        tags:  $env:DOCKER_HUB_USERNAME/$env:ANGULAR_IMAGE_NAME:$env:GITHUB_SHA

    - name: Build and push Spring Boot Image
      id: spring-boot-docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./spring-boot-oauth2-social-login
        file: ./spring-boot-oauth2-social-login/Dockerfile
        push: true
        tags:  $env:DOCKER_HUB_USERNAME/$env:SPRING_BOOT_IMAGE_NAME:$env:GITHUB_SHA

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: $env:{{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-1-20-2-do-0-blr1-1619022201280

    # Deploy the Angular Docker image to the DigitalOcean kubernetes cluster
    - name: Deploy
      run: |-
        kubectl set image deployment/$env:ANGULAR_DEPLOYMENT_NAME $env:ANGULAR_CONTAINER_NAME=$env:DOCKER_HUB_USERNAME/$env:ANGULAR_IMAGE_NAME:$env:GITHUB_SHA
        kubectl set image deployment/$env:SPRING_BOOT_DEPLOYMENT_NAME $env:SPRING_BOOT_CONTAINER_NAME=$env:DOCKER_HUB_USERNAME/$env:SPRING_BOOT_IMAGE_NAME:$env:GITHUB_SHA
        kubectl rollout status deployment/$env:ANGULAR_DEPLOYMENT_NAME
        kubectl rollout status deployment/$env:SPRING_BOOT_DEPLOYMENT_NAME
        kubectl get services -o wide
